package Forms;

import Scripts.PlayMusic;

public class Configuration extends javax.swing.JFrame {

    public PlayMusic musicPlayer = new PlayMusic();

    public Configuration() 
    {
        musicPlayer.startSong("configurationTheme", 1000);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVolume = new javax.swing.JLabel();
        btnGoBack = new javax.swing.JButton();
        sldVolumeControll = new javax.swing.JSlider();
        lblLowHigh = new javax.swing.JLabel();
        btnMuteUnmute = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblVolume.setText("VOLUME");

        btnGoBack.setText("Go Back");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        sldVolumeControll.setMajorTickSpacing(25);
        sldVolumeControll.setMinimum(50);
        sldVolumeControll.setToolTipText("");
        sldVolumeControll.setValue(musicPlayer.currentVolume);
        sldVolumeControll.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldVolumeControllStateChanged(evt);
            }
        });

        lblLowHigh.setText("LOW                HIGH");

        btnMuteUnmute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/assetMuteSound.png"))); // NOI18N
        btnMuteUnmute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuteUnmuteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblLowHigh))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGoBack)
                            .addComponent(sldVolumeControll, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMuteUnmute))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblVolume)
                .addGap(18, 18, 18)
                .addComponent(sldVolumeControll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLowHigh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnMuteUnmute)
                .addGap(49, 49, 49)
                .addComponent(btnGoBack)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMuteUnmuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuteUnmuteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMuteUnmuteActionPerformed

    private void sldVolumeControllStateChanged(javax.swing.event.ChangeEvent evt) 
    {
        int sliderValue = sldVolumeControll.getValue();

        musicPlayer.currentVolume = sliderValue;

        musicPlayer.changeVolume();

    }

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) 
    {
        MainMenu menu = new MainMenu();

        menu.setVisible(true);

        buttonAction();

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuration().setVisible(true);
            }
        });
    }

    private void buttonAction()
    {
        this.dispose();
        musicPlayer.stopSong();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JToggleButton btnMuteUnmute;
    private javax.swing.JLabel lblLowHigh;
    private javax.swing.JLabel lblVolume;
    private javax.swing.JSlider sldVolumeControll;
    // End of variables declaration//GEN-END:variables
}
