package Forms;

import java.awt.Frame;
import javax.swing.JFrame;
import Scripts.PlayMusic;

/**
 *
 * @author cristopherr
 */

public class MainMenu extends javax.swing.JFrame 
{
    private PlayMusic musicPlayer = new PlayMusic();
    
    /**
     * Creates new form MainMenu
     */
    public MainMenu() 
    {
        musicPlayer.startSong("mainTheme", 1000);
        initComponents();
        closeAllFramesExceptCurrent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMain = new javax.swing.JLabel();
        lblDificulty = new javax.swing.JLabel();
        btnEasyMode = new javax.swing.JButton();
        btnNormalMode = new javax.swing.JButton();
        btnHardMode = new javax.swing.JButton();
        btnImpossibleMode = new javax.swing.JButton();
        btnConfiguration = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMain.setText("Guesing Game");

        lblDificulty.setText("Please select the dificulty you want to play in");

        btnEasyMode.setText("EASY");
        btnEasyMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEasyModeActionPerformed(evt);
            }
        });

        btnNormalMode.setText("NORMAL");
        btnNormalMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNormalModeActionPerformed(evt);
            }
        });

        btnHardMode.setText("HARD");
        btnHardMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHardModeActionPerformed(evt);
            }
        });

        btnImpossibleMode.setText("IMPOSSIBLE");
        btnImpossibleMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpossibleModeActionPerformed(evt);
            }
        });

        btnConfiguration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/assetConfiguration.png"))); // NOI18N
        btnConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigurationActionPerformed(evt);
            }
        });

        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/assetHowToPlay.png"))); // NOI18N
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(lblMain))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEasyMode, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnNormalMode, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnHardMode, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnImpossibleMode, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblDificulty)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnConfiguration)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHelp)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblMain)
                .addGap(34, 34, 34)
                .addComponent(lblDificulty)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEasyMode, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNormalMode, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImpossibleMode, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHardMode, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfiguration)
                    .addComponent(btnHelp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfigurationActionPerformed(java.awt.event.ActionEvent evt) 
    {
        Configuration configuration = new Configuration();

        configuration.setVisible(true);

        buttonAction();
    }

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) 
    {

        buttonAction();
    }

    
    private void btnEasyModeActionPerformed(java.awt.event.ActionEvent evt) 
    {
        EasyMode easyMode = new EasyMode();
        
        easyMode.setVisible(true);

        buttonAction();
    }
    
    private void btnNormalModeActionPerformed(java.awt.event.ActionEvent evt) 
    {
        NormalMode normalMode = new NormalMode();
        
        normalMode.setVisible(true);

        buttonAction();
    }
    
    private void btnHardModeActionPerformed(java.awt.event.ActionEvent evt) 
    {
        HardMode hardMode = new HardMode();
        
        hardMode.setVisible(true);

        buttonAction();
    }

    private void btnImpossibleModeActionPerformed(java.awt.event.ActionEvent evt) 
    {
        ImpossibleMode impossibleMode = new ImpossibleMode();

        impossibleMode.setVisible(true);

        buttonAction();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
     

    private void closeAllFramesExceptCurrent() 
    {
        Frame[] frames = Frame.getFrames(); // Obtiene todos los marcos activos

        for (Frame frame : frames) 
        {
            if (frame instanceof JFrame && frame != this) 
            {
                frame.dispose();
            }
        }
    }

    private void buttonAction()
    {
        musicPlayer.stopSong();
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfiguration;
    private javax.swing.JButton btnEasyMode;
    private javax.swing.JButton btnHardMode;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnImpossibleMode;
    private javax.swing.JButton btnNormalMode;
    private javax.swing.JLabel lblDificulty;
    private javax.swing.JLabel lblMain;
    // End of variables declaration//GEN-END:variables
}
